### PR TITLE
Update facemap_select.py  with Ui List

### PR DESCRIPTION
**Pull request by TYO79**
1) Last FaceMap created becomes Active.  change "Facemap" for "FaceMap"

2) Added Ui Lists to Dreate, Delete, Assign, Remove, Select and Deselect FaceMap to Selection

3) Only miss the Up and Down operator

### CODE REVIEW

**Comment by varkenvarken** [comment]
hi Andrew,

Looks good, much appreciated! Will test it as soon as possible 

-- Michel

**Comment by TYO79** [comment]
hi Michel,

my name is Yann;), wasn't sure your branch was still active, so i made my
own git with it. I kept your names for contribution of course;)

Best regards

Cordialement...


////////////////////////////////// Yann Terrer
//////////////// ***@***.***
//////////////// tel: + 33 6 63 10 92 62
///////////////////// www.yannterrer.com


Le mar. 5 nov. 2024 à 08:35, Michel Anders ***@***.***> a
écrit :

**Comment by varkenvarken** [comment]
Oops, sorry :-)

and yes the blenderaddons repository is still alive & contributions are always appreciated.

**Comment by varkenvarken** [comment]
thanks for the PR. tweaked it just a tiny bit (mainly the Black formatter) and made sure that an newly created facemap is made active so that select etc. immediately work. I think I will revisit this addon to make sure that when a facemap is deleted, another one (if present) is made active and/or that the extra operators check if there is an active facemap

**Pull request merged**
